Add `CtOption::into_option`
dalek-cryptography/subtle pull request #119
Opened 2024-02-02 00:51 UTC by tarcieri

A small wrapper for `impl CtOption<T> for Option<T>` which is friendlier for type inference purposes.

Using `Option::from(ct_option)` often doesn't work because the compiler is unable to infer `T` for `Option<T>`, so you have to manually annotate `Option::<T>::from`.

In practice this often winds up looking like:

    Option::<T>::from(T::constructor(x))`

which feels quite redundant.

Using an inherent method instead fixes type inference so the above can be:

    T::constructor(x).into_option()

2024-02-02 01:27 UTC, tarcieri commented
https://github.com/RustCrypto/signatures/pull/804/files contains a more concrete example:

```rust
Option::<C::Uint>::from(
    C::Uint::decode_field_bytes(&r.to_repr()).checked_add(&C::ORDER),
)
.ok_or_else(Error::new)?
.encode_field_bytes()
```

...could instead be:

```rust
C::Uint::decode_field_bytes(&r.to_repr())
    .checked_add(&C::ORDER)
    .into_option()
    .ok_or_else(Error::new)?
    .encode_field_bytes()
```

2024-02-08 16:21 UTC, AaronFeickert requested changes

2024-02-08 16:21 UTC, AaronFeickert commented on src/lib.rs
> +    /// It's equivalent to the corresponding `From` impl, however this version is is
```suggestion
    /// It's equivalent to the corresponding `From` impl, however this version is
```

2024-02-08 16:32 UTC, AaronFeickert approved these changes
Very convenient to have this wrapper, thanks!

2024-02-09 20:24 UTC, isislovecruft approved these changes
Hi @tarcieri! Hi @AaronFeickert!

Thanks so much for the PR, this wrapper is very conveniant.

2024-02-09 20:27 UTC, merged

2024-02-09 20:57 UTC, AaronFeickert commented
All credit goes to @tarcieri for sure!